### ISSUE TITLE
BUG: ExportPals

### ISSUE THREAD

**Issue by ronglee0** [CerisWhite/Lantern#5]
Version:v1.5.2 win

in level.sav.json one player's nickname
```
													"NickName": {
														"id": null,
														"value": "< blank >",
														"type": "StrProperty"
													},
```

```
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\dooki\Desktop\PalSave\lantern_v152_win\Save\PalData\Player\< blank >_75f977b7-ac5e-44f3-9772-48b03109aced.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1283:35)
    at Stream.<anonymous> (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\Lantern.js:1:71987)
    at Stream.emit (events.js:310:20)
    at drain (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\through\index.js:36:16)
    at Stream.stream.queue.stream.push (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\through\index.js:45:5)
    at Parser.parser.onValue (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\JSONStream\index.js:118:16)
    at Parser.proto.emit (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\jsonparse\jsonparse.js:337:8)
    at Parser.proto.pop (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\jsonparse\jsonparse.js:332:8)
    at Parser.proto.onToken (C:\Users\dooki\Desktop\PalSave\lantern_v152_win\node_modules\jsonparse\jsonparse.js:402:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\dooki\\Desktop\\PalSave\\lantern_v152_win\\Save\\PalData\\Player\\< blank >_75f977b7-ac5e-44f3-9772-48b03109aced.json'
}

```

Great tool

**Comment by CerisWhite** [comment]
Windows may not like the use of `<` and `>` in file names. Otherwise I'm really not sure what it could be.
